export const ROLES = {
  principal: {
    id: "principal",
    name: "Dr. V. Ravindra",
    title: "Principal & Head of Institution",
    roleTag: "CAMPUS HEAD",
    badgeClass: "principal",
    avatar: "P",
    email: "principal@college.edu",
    password: "PrincipalPass123!",
    department: "ALL",
    scopeLabel: "All Departments (CSE, ECE, MECH, CIVIL, EEE)",
  },
  dean: {
    id: "dean",
    name: "Dr. K. Sarojini",
    title: "Dean / Vice Principal (Academics)",
    roleTag: "ACADEMIC DEAN",
    badgeClass: "dean",
    avatar: "D",
    email: "dean@college.edu",
    password: "DeanPass123!",
    department: "ALL",
    scopeLabel: "Campus Academic Monitoring & Verification",
  },
  hod_cse: {
    id: "hod_cse",
    name: "Dr. K. Ramesh",
    title: "Head of Department (CSE)",
    roleTag: "HOD - CSE",
    badgeClass: "hod",
    avatar: "C",
    email: "hod.cse@college.edu",
    password: "HodPass123!",
    department: "CSE",
    scopeLabel: "Computer Science & Engineering Department",
  },
  hod_ece: {
    id: "hod_ece",
    name: "Dr. M. Sreenivasulu",
    title: "Head of Department (ECE)",
    roleTag: "HOD - ECE",
    badgeClass: "hod",
    avatar: "E",
    email: "hod.ece@college.edu",
    password: "HodPass123!",
    department: "ECE",
    scopeLabel: "Electronics & Communication Department",
  },
  admin: {
    id: "admin",
    name: "System Administrator",
    title: "AMS Lead Administrator",
    roleTag: "ADMINISTRATOR",
    badgeClass: "principal",
    avatar: "A",
    email: "admin@college.edu",
    password: "AdminPass123!",
    department: "ALL",
    scopeLabel: "Full System Audit & Management",
  },
};
